import {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { getStories } from '../server/stories';
import { StoryPost } from '../src/types/story';
import styles from '../styles/Home.module.scss';

const Home: NextPage = ({
  storiesData,
  chaptersData,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className="flex flex-col items-center text-[1.15rem] mt-12">
          <div className="flex gap-3 mb-12">
            {chaptersData.map((tag: string, idx: number) => {
              return (
                <button key={idx} onClick={(e) => {}}>
                  {tag}
                </button>
              );
            })}
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  let stories: StoryPost[] = await getStories('DIC_kwDOIbAdhM4CSvMs');
  let chapters: string[] = [];
  for (const story of stories) {
    for (const chapter of story.chapters) {
      if (!chapters.includes(chapter)) {
        chapters.push(chapter);
      }
    }
  }
  return {
    props: {
      storiesData: stories,
      chaptersData: chapters,
    },
  };
};
